spring:
  application:
    name: spring-core
  profiles:
    active:
  lifecycle:
    timeout-per-shutdown-phase: 40s # this is for graceful shutdown

orbit:
  todo:
    id-strategy: uuid
    default-status: PENDING
    max-per-project: 100
    cleanup-enabled: false
    cleanup-interval: PT30M

  project:
    default-limit: 10
logging:
  level:
    com.onatarslan.springcore.todo: debug # perfect setting when you debug one package :)
    com.onatarslan.springcore: info
    root: info



